version: '3.7'
services:
  miniserve:
    image: svenstaro/miniserve:latest
    container_name: miniserve
    ports:
      - "4534:8080"
    volumes:
      - "/tmp/data_docker/data:/data"
    # admin:123456 修改成自己的账号:密码
    command: "-r -z -u -q -p 8080 -a admin:123456 /data"
    restart: unless-stopped