version: '3.7'
services:
  etcd:
    image: "quay.io/coreos/etcd:v3.4.7"
    # 容器启动后执行的命令
    entrypoint: /usr/local/bin/etcd
    # 参数
    command:
      - '--name=etcd'
      - '--data-dir=/etcd_data'
      - '--initial-advertise-peer-urls=http://etcd1:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd1:2379'
      - '--initial-cluster-token=123456'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd1=http://etcd1:2380'
      - '--initial-cluster-state=new'
    ports:
      - 2379:2379
      - 2380:2380
    volumes:
      - ./data:/etcd_data