version: '3.3'

services:
  samba:
    image: dperson/samba
    container_name: samba-shared
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: false
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./config/smb.conf:/etc/samba/smb.conf
      - /home/shared:/mnt:z
      #- /mnt2:/mnt2:z
    command: '-s "samba;/mnt;yes;no;no;zhangyan" -u "zhangyan;123456" -p'
    #command: '-s "Mount;/mnt" -s "Bobs Volume;/mnt2;yes;no;no;bob" -u "bob;bobspasswd" -p'

networks:
  default:
