services:
  minio:
    image: minio/minio:RELEASE.2024-10-29T16-01-48Z
    container_name: minio
    ports:
      - 9000:9000
      # new version
      - 9001:9001
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    volumes:
      - /data/minio:/data
    # new version
    command: server --console-address ':9001' /data
    #command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
