version: '3.7'
services:
  mysql:
    image: mysql:5.7.38
    container_name: mysql57
    restart: always
    volumes:
      # 该目录下可放置初始化sql文件，以文件名字母顺序执行
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ./conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD
    command: ["--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci","--default-time-zone=+8:00","--max_connections=5000"]

volumes:
  data: