version: "3.3"
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ="Asia/Shanghai"
      - PLEX_CLAIM=claim-znQrdDAhEVatd_xkx1rp
      #- ADVERTISE_IP=http://<hostIPAddress>:32400/
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config:/config
      - ./transcode:/transcode
      - ./media:/data
      - /home/video:/video
