version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: minio/minio:RELEASE.2021-06-17T00-10-46Z
  command: server http://minio{1...4}/data{1...2}
  restart: always
  expose:
    - "9000"
  environment:
    - MINIO_ACCESS_KEY
    - MINIO_SECRET_KEY
    - MINIO_REGION
    - MINIO_DOMAIN
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - /data-1/data1:/data1
      - /data-1/data2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - /data-2/data1:/data1
      - /data-2/data2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - /data-3/data1:/data1
      - /data-3/data2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - /data-4/data1:/data1
      - /data-4/data2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /data/logs/minio_nginx_log:/var/log/nginx
    ports:
      - "9000:9000"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

