services:
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - 5540:5540
    #volumes:
    #  - /data/redis-insight/data:/data

# volumes:
#   redisinsight_data:
#     driver: local
#   redisinsight_logs:
#     driver: local