version: '3.9'
services:
  postgis:
    image: postgis/postgis:16-3.4-alpine
    container_name: postgis
    restart: always
    environment:
      - LANG=zh_CN.utf8
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      # - ./init-scripts:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data
      - backup:/backup

volumes:
  data:
  backup:
