
networks:
  redis-network:
    name: redis-network

redis-cluster: &redis-cluster
  image: redis:7-alpine
  command: redis-server /usr/local/etc/redis/redis.conf
  restart: always
  networks:
    redis-network:

services:
  redis-6371:
    <<: *redis-cluster
    container_name: redis-6371
    hostname: redis-6371
    ports:
      - "6371:6371"
    volumes:
      - "./conf/6371/conf/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./conf/6371/data:/data"

  redis-6372:
    <<: *redis-cluster
    container_name: redis-6372
    hostname: redis-6372
    ports:
      - "6372:6372"
    volumes:
      - "./conf/6372/conf/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./conf/6372/data:/data"

  redis-6373:
    <<: *redis-cluster
    container_name: redis-6373
    hostname: redis-6373
    ports:
      - "6373:6373"
    volumes:
      - "./conf/6373/conf/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./conf/6373/data:/data"

  redis-6374:
    <<: *redis-cluster
    container_name: redis-6374
    hostname: redis-6374
    ports:
      - "6374:6374"
    volumes:
      - "./conf/6374/conf/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./conf/6374/data:/data"

  redis-6375:
    <<: *redis-cluster
    container_name: redis-6375
    hostname: redis-6375
    ports:
      - "6375:6375"
    volumes:
      - "./conf/6375/conf/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./conf/6375/data:/data"

  redis-6376:
    <<: *redis-cluster
    container_name: redis-6376
    hostname: redis-6376
    ports:
      - "6376:6376"
    volumes:
      - "./conf/6376/conf/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./conf/6376/data:/data"
