version: '3.7'
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    ports:
      # 左边可以改成自己服务器未被占用的端口
      - "4533:4533"
    environment:
      # Optional: put your config options customization here. Examples(这些都是可选的):
      - ND_SCANSCHEDULE
      - ND_LASTFM_ENABLED
      # 修改成自己的APIKEY
      - ND_LASTFM_APIKEY
      # 修改成自己的SECRET
      - ND_LASTFM_SECRET
      # 修改成自己的ID
      - ND_SPOTIFY_ID
      # 修改成自己的SECRET
      - ND_SPOTIFY_SECRET
      - ND_LASTFM_LANGUAGE
      - ND_LOGLEVEL
      - ND_SESSIONTIMEOUT
      - ND_BASEURL
    volumes:
      - "/tmp/lima/data_docker/music/config:/data"
      # 冒号左边修改成自己本地的音乐文件夹路径
      - "/tmp/lima/data_docker/music/data:/music:ro"

  miniserve:
    image: svenstaro/miniserve:latest
    container_name: miniserve
    depends_on:
      - navidrome
    ports:
      - "4534:8080"
    volumes:
      # 冒号左边修改成自己本地的音乐文件夹路径
      - "/tmp/lima/data_docker/music/data:/downloads"
    # admin:123456 修改成自己的账号:密码
    command: "-r -z -u -q -p 8080 -a admin:123456 /downloads"
    restart: unless-stopped