version: '3.9'
services:
  registry:
    image: registry:2
    container_name: registry
    hostname: registry
    restart: always
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    ports:
      - 5000:5000
    volumes:
      - /data/registry:/var/lib/registry

  registry-web:
    image: hyper/docker-registry-web
    container_name: registry-web
    hostname: registry-web
    restart: always
    ports:
      - 8080:8080
    #environment:
      #- REGISTRY_URL=http://registry:5000/v2
      #- REGISTRY_NAME=localhost:5000
    volumes:
      - ./config.yml:/conf/config.yml
    depends_on:
      - registry