version: '3.7'
services:
  test-rabbitmq:
    image: rabbitmq:3.11.13-management
    container_name: test-rabbitmq3.11.13
    hostname: rabbitmq
    restart: always
    volumes:
      - ./data:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS