services:
  my-gitlab:
    image: 'gitlab/gitlab-ce:18.2.0-ce.0'
    container_name: my-gitlab
    restart: always
    hostname: 'cuilan.gitlab.com'
    #network_mode: "host"
    ports:
      - '9080:80'
      - '9443:443'
      - '9022:22'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://10.10.5.3'
        # Add any other gitlab.rb configuration here, each on its own line
    volumes:
      - /home/gitlab/config:/etc/gitlab
      - /home/gitlab/logs:/var/log/gitlab
      - /home/gitlab/data:/var/opt/gitlab
