version: '3.7'
services:
  my-gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: my-gitlab
    #restart: always
    hostname: 'cuilan.gitlab.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://10.10.5.3'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '9080:80'
      #- '9443:443'
      - '9022:22'
    volumes:
      - /home/gitlab/config:/etc/gitlab
      - /home/gitlab/logs:/var/log/gitlab
      - /home/gitlab/data:/var/opt/gitlab
