version: '3.7'
services:
  nginx:
    #restart: always
    image: nginx:1.21-alpine
    container_name: nginx-1-21-alpine
    ports:
      - '80:80'
    volumes:
      - "./conf.d/nginx.conf:/etc/nginx/nginx.conf"
      - "./html:/usr/share/nginx/html"
    #environment:
      #- NGINX_PORT=80
      #- NGINX_HOST=www.cuilan.com
