version: '3.9'
services:
  coredns:
    image: coredns/coredns:1.9.3
    container_name: coredns
    network_mode: "host"
    restart: always
    volumes:
      - ./coredns:/etc/coredns
    command: -conf=/etc/coredns/Corefile
    cpus: '2.0'
    mem_limit: 2g
    mem_reservation: 512m