services:
  nfs-server:
    image: erichough/nfs-server:2.2.1
    container_name: nfs-server
    restart: unless-stopped
    privileged: true
    volumes:
      # 定义容器内共享目录、权限
      - ./exports:/etc/exports:ro
      # 定义挂载目录，要写必须明确指出rw权限
      - /data:/data:rw
    ports:
      # NFSv4 only
      - 2049:2049
      # NFSv3
      # - 2049:2049
      # - 2049:2049/udp
      # - 111:111
      # - 111:111/udp
      # - 32765:32765 
      # - 32765:32765/udp
      # - 32767:32767
      # - 32767:32767/udp
