version: '3.9'
services:
  pgsql:
    image: postgres:16.2-alpine3.19
    container_name: pgsql
    restart: always
    environment:
      - LANG=zh_CN.utf8
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      # - POSTGRES_PASSWORD_FILE=/run/secrets/password
      # - POSTGRES_INITDB_ARGS
      # - POSTGRES_INITDB_WALDIR
      # - POSTGRES_HOST_AUTH_METHOD
      # - PGDATA=/var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      # - ./init-scripts:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data
      - backup:/backup

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  data:
  backup:
