version: '3.7'
services:
  nginx:
    image: nginx:1.21-alpine
    container_name: nginx-1-21-alpine
    restart: always
    network_mode: "host"
    environment:
      TZ: Asia/Shanghai
    ports:
      - '80:80'
    volumes:
      - /etc/timezone:/etc/timezone
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
      - ./common:/etc/nginx/common
      - /data/logs/nginx:/var/log/nginx/
