services:
  redis:
    image: redis:7-alpine
    # 容器名
    container_name: redis7-alpine
    #restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - "./data:/data"
      - "./conf/redis.conf:/usr/local/etc/redis/redis.conf"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 15s
      retries: 3
    #command: redis-server --appendonly yes --requirepass 123456
