services:
  test-rabbitmq:
    image: rabbitmq:3.11.13-management
    container_name: test-rabbitmq3.11.13
    hostname: rabbitmq
    restart: always
    volumes:
      - ./data:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
    cpus: '2.0'
    mem_limit: 2g
    mem_reservation: 1g
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/127.0.0.1/5672'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s