version: '3.9'
services:
  mysql:
    # 构建mysql镜像
    image: mysql:8
    # 容器名
    container_name: mysql-db
    platform: linux/amd64
    #restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD
    ports:
      - '3306:3306'
    volumes:
      # 容器的配置目录挂载到host物理机目录./conf
      #- ./conf:/etc/mysql/conf.d
      - ./init-scripts:/docker-entrypoint-initdb.d
      - data:/var/lib/mysql
      # - "/tmp/lima/data_docker/mysql/db:/var/lib/mysql"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  data: