version: '3.7'
services:
  my-minio:
    image: 'minio/minio:RELEASE.2021-06-17T00-10-46Z'
    container_name: my-minio
    ports:
      - '9000:9000'
        # new version
      #- '9001:9001'
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    volumes:
      - /data_minio:/data
    # new version
    #command: server --console-address ':9001' /data
    command: server /data
